on: [push, pull_request]

name: CI

jobs:
  test-posix:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.4.0, 12.x, 14.x, 15.x]
        exclude:
          - os: windows-latest
            node-version: 12.4.0 # The node-gyp shipped with this is too old
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          check-latest: true
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Test
        run: npm test
